from pathlib import Path


PNG_STORYBOARDS_ROOT = Path(__file__).resolve().parent / "png_storyboards"

BLOCK_01_PHASOR_INTRO = PNG_STORYBOARDS_ROOT / "01_phasor_intro"
BLOCK_02_FOURIER_TRANSFORMATION = PNG_STORYBOARDS_ROOT / "02_fourier_transformation"
BLOCK_03_REALE_AUDIOSIGNALE = PNG_STORYBOARDS_ROOT / "03_reale_audiosignale"
BLOCK_04_INVERSE_FOURIERTRANSFORMATION = PNG_STORYBOARDS_ROOT / "04_inverse_fouriertransformation"
BLOCK_05_INVERSE_FOURIERTRANSFORMATION_MIT_FENSTERUNG = PNG_STORYBOARDS_ROOT / "05_inverse_ft_mit_fensterung"
BLOCK_06_AUFGABEN = PNG_STORYBOARDS_ROOT / "06_aufgaben"

PHASOR_INTRO_DIR = BLOCK_01_PHASOR_INTRO / "01A_phasor_intro_und_grundbilder"

FOURIER_TRANSFORMATION_DIR = BLOCK_02_FOURIER_TRANSFORMATION
FOURIER_PROBE_SERIES_DIR = BLOCK_02_FOURIER_TRANSFORMATION / "02A_fourier_probe_serien"
TWO_SIDED_SINE_DIR = BLOCK_02_FOURIER_TRANSFORMATION / "02B_two_sided_sine_spectrum"
TWO_SIDED_COSINE_DIR = BLOCK_02_FOURIER_TRANSFORMATION / "02C_two_sided_cosine_spectrum"
MIXED_SIGNAL_TWO_SIDED_SPECTRUM_DIR = BLOCK_02_FOURIER_TRANSFORMATION / "02D_mixed_signal_two_sided_spectrum"
ONE_SIDED_WINDOWED_MIXED_SIGNAL_DIR = BLOCK_02_FOURIER_TRANSFORMATION / "02E_one_sided_windowed_mixed_signal"

PHASE_SHIFT_INTRO_DIR = BLOCK_03_REALE_AUDIOSIGNALE / "03A_phase_shift_intro"
PHASE_SHIFT_SERIES_DIR = BLOCK_03_REALE_AUDIOSIGNALE / "03B_phase_shift_series"
PHASE_SHIFT_SERIES_COS_NO_COMPONENTS_DIR = BLOCK_03_REALE_AUDIOSIGNALE / "03C_phase_shift_series_cos_no_components"
PHASE_SHIFT_SERIES_MIXED_EXTRACTED_DIR = BLOCK_03_REALE_AUDIOSIGNALE / "03D_phase_shift_series_mixed_extracted"

INVERSE_FOURIERTRANSFORMATION_DIR = BLOCK_04_INVERSE_FOURIERTRANSFORMATION
INVERSE_FT_STORYBOARD_SERIES_DIR = BLOCK_04_INVERSE_FOURIERTRANSFORMATION / "04A_inverse_ft_storyboard_serien"
INVERSE_FT_ONE_SIDED_STORYBOARD_T0P18_DIR = (
    BLOCK_04_INVERSE_FOURIERTRANSFORMATION / "04B_inverse_ft_one_sided_storyboard_t0p18"
)
INVERSE_FOURIERTRANSFORMATION_WINDOWED_DIR = BLOCK_05_INVERSE_FOURIERTRANSFORMATION_MIT_FENSTERUNG

HOMEWORK_RECONSTRUCTION_DIR = BLOCK_06_AUFGABEN / "06A_homework_reconstruction_spectra"
HOMEWORK_MATCH_TIME_TO_SPECTRUM_DIR = BLOCK_06_AUFGABEN / "06B_zeitfunktion_zu_spektrum_waehlen"


def fourier_probe_dir(freq_slug: str) -> Path:
    return FOURIER_PROBE_SERIES_DIR / f"02A_probe_{freq_slug}_hz"
